apiVersion: v2
name: grocery-optimizer
description: Grocery Price Optimizer (FastAPI API + React UI in one container)
type: application
version: 0.1.0        # version of this chart
appVersion: "0.1.0"   # version of the app image it deploys
